// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqg9FiNmR68KVNrIUlydHEJtRj3cCH8xg',
    appId: '1:809940212396:web:51bb836258dd77f4769d09',
    messagingSenderId: '809940212396',
    projectId: 'chat-app-f653c',
    authDomain: 'chat-app-f653c.firebaseapp.com',
    storageBucket: 'chat-app-f653c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOZMuWIfOpevwM0RFjRApQeGc8hQ8tCEY',
    appId: '1:809940212396:android:a8b7ff80386d4498769d09',
    messagingSenderId: '809940212396',
    projectId: 'chat-app-f653c',
    storageBucket: 'chat-app-f653c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqTUHTia63vdU2fvq0rHkYcG6m5vQBYhY',
    appId: '1:809940212396:ios:f33de96b17422d99769d09',
    messagingSenderId: '809940212396',
    projectId: 'chat-app-f653c',
    storageBucket: 'chat-app-f653c.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqTUHTia63vdU2fvq0rHkYcG6m5vQBYhY',
    appId: '1:809940212396:ios:7dbf8dd54bd97576769d09',
    messagingSenderId: '809940212396',
    projectId: 'chat-app-f653c',
    storageBucket: 'chat-app-f653c.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
